version: "3.0"
services:
  faas-gateway:
    build:
      context: ./faas-gateway
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mathoperations:
    build:
      context: ./mathoperations
    labels:
      - "faas.name=mathoperations"
      - "faas.port=8080"
  ping:
    build:
      context: ./ping
    labels:
      - "faas.name=ping"
      - "faas.port=8080"