version: "3.0"
services:
  faas-gateway:
    build:
      context: ./faas-gateway
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./faas-gateway:/go/src/github.com/tangyuan2014/modularfianicefaas/faas-gateway
  mathoperations:
    build:
      context: ./mathoperations
    labels:
      - "faas.name=mathoperations"
      - "faas.port=8080"
    volumes:
      - ./mathoperations:/go/src/github.com/tangyuan2014/modularfianicefaas/mathoperations
  currentweather:
    build:
      context: ./currentweather
    labels:
      - "faas.name=currentweather"
      - "faas.port=8080"
    volumes:
      - ./currentweather:/go/src/github.com/tangyuan2014/modularfianicefaas/currentweather
